definitions:
  request.DataRequest:
    properties:
      data_id:
        type: string
      payload:
        type: string
      user_id:
        type: string
    required:
    - data_id
    - payload
    - user_id
    type: object
  response.ResponseHTTP:
    properties:
      error_code:
        type: integer
      message:
        type: string
    type: object
info:
  contact: {}
paths:
  /data:
    post:
      consumes:
      - application/json
      description: Send data to the server and return the result
      parameters:
      - description: Data to send
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.DataRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ResponseHTTP'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ResponseHTTP'
        "429":
          description: Too Many Requests
          schema:
            $ref: '#/definitions/response.ResponseHTTP'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ResponseHTTP'
      summary: Send data to the server
      tags:
      - Data
swagger: "2.0"
